package screen;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import model.FileMessage;

public class RepoProperties extends javax.swing.JFrame {

    /**
     * Creates new form RepoProperties
     */
    public RepoProperties(ArrayList<FileMessage> fileMessageList) {
        initComponents();
        RepoProperties.this.setVisible(true);
        RepoProperties.this.setTitle("Propriedades");
        RepoProperties.this.setDefaultCloseOperation(HIDE_ON_CLOSE);

        centralizeScreen();

        getInfos(fileMessageList);
    }

    private void centralizeScreen() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    private void getInfos(ArrayList<FileMessage> fileMessageList) {

        int numberOfFiles = 0;
        int usedSize = 0;
        int largestSize;
        String largestFile;
        String extFile;
        int numberOfPhotos = 0;
        int numberOfVideos = 0;
        int numberOfAudios = 0;
        int numberOfTexts = 0;
        int numberOfUnrecognized = 0;

        largestSize = fileMessageList.get(0).getFileSize();
        largestFile = fileMessageList.get(0).getFilename();
        extFile = fileMessageList.get(0).getFileType();

        for (FileMessage fm : fileMessageList) {
            numberOfFiles++;
            usedSize += fm.getFileSize();

            if (fm.getFileSize() > largestSize) {
                largestFile = fm.getFilename();
                extFile = fm.getFileType();
            }

            switch (fm.getFileType()) {
                case "png":
                case "jpg":
                case "jpeg":
                    numberOfPhotos++;
                    break;
                case "avi":
                case "mov":
                case "wmv":
                case "mp4":
                case "flv":
                case "mkv":
                case "rm":
                    numberOfVideos++;
                    break;
                case "dts":
                case "ac3":
                case "mp3":
                    numberOfAudios++;
                    break;
                case "txt":
                case "doc":
                case "xml":
                case "docx":
                case "xlsx":
                case "pptx":
                case "pdf":
                    numberOfTexts++;
                    break;
                default:
                    numberOfUnrecognized++;
            }
        }
        
        this.numberLabel.setText(Integer.toString(numberOfFiles));
        this.usedLabel.setText(Integer.toString(usedSize) + "B");
        this.largestLabel.setText(largestFile + "." + extFile);
        this.audioLabel.setText(Integer.toString(numberOfAudios));
        this.photoLabel.setText(Integer.toString(numberOfPhotos));
        this.textLabel.setText(Integer.toString(numberOfTexts));
        this.videoLabel.setText(Integer.toString(numberOfVideos));
        this.unrecognizedLabel.setText(Integer.toString(numberOfUnrecognized));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        usedLabel = new javax.swing.JLabel();
        largestLabel = new javax.swing.JLabel();
        audioLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        videoLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        unrecognizedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Quantidade de arquivos:");

        jLabel2.setText("Total de espaço utilizado:");

        jLabel3.setText("Maior arquivo:");

        jLabel4.setText("Quantidade de fotos:");

        jLabel5.setText("Quantidade de textos:");

        jLabel6.setText("Quantidade de vídeos:");

        jLabel7.setText("Quantidade de áudios:");

        numberLabel.setText("jLabel8");

        usedLabel.setText("jLabel9");

        largestLabel.setText("jLabel10");

        audioLabel.setText("jLabel11");

        photoLabel.setText("jLabel12");

        textLabel.setText("jLabel13");

        videoLabel.setText("jLabel14");

        jLabel8.setText("Extensões desconhecidas:");

        unrecognizedLabel.setText("jLabel15");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usedLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(largestLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unrecognizedLabel)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numberLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usedLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(largestLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(audioLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(photoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(videoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(unrecognizedLabel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel audioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel largestLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel unrecognizedLabel;
    private javax.swing.JLabel usedLabel;
    private javax.swing.JLabel videoLabel;
    // End of variables declaration//GEN-END:variables
}
